const championListAutocomplete = [
	'Taras the Fierce',
	'Siphi the Lost Bride',
	'Seer',
	'Scyl of the Drakes',
	'Sicia Flametongue',
	'Sir Nicholas',
	'Staltus Dragonbane',
	'Stag Knight',
	'Teodor the Savant',
	'Teumesia',
	'Trunda Giltmallet',
	'Turvold',
	'Tuhanarak',
	'Tatura Rimehide',
	'Underpriest Brogni',
	'Mighty Ukko',
	'Uugo',
	'Valkyrie',
	'Venus',
	'Vogoth',
	'Warlord',
	'Whisper',
	'Yumeko',
	'Lydia the Deathsiren',
	'Hierophant Lazarius',
	'Leorius the Proud',
	'Lyssandra',
	'Ma\'Shalled',
	'Maneater',
	'Marichka the Unbreakable',
	'Mithrala Lifebane',
	'Michinaki',
	'Nekhret the Great',
	'Nekmo Thaar',
	'Ninja',
	'Pythion',
	'Quintus the Triumphant',
	'Ragash',
	'Ramantu Drakesblood',
	'R. Nergigante Archer',
	'Riho Bonespear',
	'Prince Kymar',
	'Kyoku',
	'Krisk the Ageless',
	'Kalvalax',
	'Bad-el-Kazar',
	'Baron',
	'Acrizia',
	'Androc The Glorious',
	'Arbiter',
	'Dark Kael',
	'Deacon Armstrong',
	'Demytha',
	'Duchess Lilitu',
	'Dracomorph',
	'Drexthar Bloodtwin',
	'Elva Autumnborn',
	'Firrol The Barkhorn',
	'Gnut',
	'Graazur Irongut',
	'Godseeker Aniri',
	'Geomancer',
	'Acelin The Stalwart',
	'Alatreon Blademaster',
	'Aox the Rememberer',
	'Akemtum',
	'Aphidus The Hivelord',
	'Alure',
	'Alaz The Sunbearer',
	'Archmage Hellmut',
	'Archbishop Pinthroy',
	'Arbais the Stonethorn',
	'Armanz the Magnificent',
	'Armiger',
	'Artak',
	'Ba Satha',
	'Belanor',
	'Belletar Mage-slayer',
	'Blizaar The Howler',
	'Blind Seer',
	'Bivald of the Thorn',
	'Chaagur',
	'Candraphon',
	'Claidna',
	'Coldheart',
	'Conellia',
	'Countess Lix',
	'Crypt-King Graal',
	'Crohnam',
	'Dhukk the Pierced',
	'Doompriest',
	'Walking Tomb Dreng',
	'Elder Skarg',
	'Emic Trunkheart',
	'Fahrakin the Fat',
	'Fenax',
	'Frolni the Mechanist',
	'Fu-Shan',
	'Starsage Galathir',
	'Genbo the Dishonored',
	'Georgid the Breaker',
	'Ghostborn',
	'Gharol Bloodmaul',
	'Ghrush the Mangler',
	'Gizmak The Terrible',
	'Gliseah Soulguide',
	'Gomlok Skyhide',
	'Gronjarr',
	'Gwyndolin The Silent',
	'Hegemon',
	'Hephraak',
	'High Khatun',
	'Holsring',
	'Hotatsu',
	'Husk',
	'Ignatius',
	'Inquisitor Shamael',
	'Iron Brago',
	'Ithos',
	'Jagg Bonesaw',
	'Jintoro',
	'Jetni The Giant',
	'Karnage the Anarch',
	'Kael',
	'Kaja the Wry',
	'Kantra the Cyclone',
	'Karato Foxhunter',
	'Keeyra the Watcher',
	'Khoronar',
	'King Gallcobar',
	'Night Queen Krixia',
	'Kreela Witch-Arm',
	'Krok’mar the Devourer',
	'Korugar Death-Bell',
	'Konstantin the Dayborn',
	'Lady Mikage',
	'Lady of Ireth',
	'Lord Champfort',
	'Highmother Maud',
	'Madame Serris',
	'Magnarr',
	'Mausoleum Mage',
	'Marius the Gallant',
	'Martyr',
	'Melga Steelgirdle',
	'Miscreated Monster',
	'Mordecai',
	'Morrigaine',
	'Wight King Narses',
	'Neldor Rimeblade',
	'Nethril',
	'Noct',
	'Myciliac Priest Orn',
	'Ostrox Boneglaive',
	'Oella',
	'Grand Oak Padraig',
	'Psylar',
	'Raglin',
	'Rakka Viletide',
	'Rae',
	'Rector Drath',
	'Renegade',
	'Richtoff the Bold',
	'Rian the Conjurer',
	'Roshcard the Tower',
	'Roxam',
	'Royal Guard',
	'Royal Huntsman',
	'Greenwarden Ruarc',
	'Ruel the Huntmaster',
	'Ruella',
	'Runekeeper Dazdurk',
	'Rotos the Lost Groom',
	'Searsha The Charred',
	'Seeker',
	'Sethallia',
	'Shemnath',
	'Shu-Zhen the Valorous',
	'Skraank',
	'SkullCrown',
	'Sniktraak',
	'Soulless',
	'Supreme Elhain',
	'Supreme Galek',
	'Supreme Kael',
	'Sun Wukong',
	'Sulfuryion',
	'Tayrel',
	'Togron the Conjoined',
	'Tomb Lord',
	'Toragi The Frog',
	'Truath',
	'Tyrant Ixlimor',
	'Ugir the Wyrmeater',
	'Ultimate Deathknight',
	'Umbral Enchantress',
	'Ursala the Mourner',
	'Ursuga Warcaller',
	'Urost the Soulcage',
	'Urogrim',
	'Valkanen',
	'Vasal of the Seal',
	'Venomage',
	'Vitrius the Anointed',
	'Vitrius the Anointed',
	'Wythir the Crowned',
	'Xena: Warrior Princess',
	'Yannica',
	'Yakarl the Scourge',
	'Zinogre Blademaster',
	'Zavia',
	'Warcaster',
	'Norog',
	'Achak',
	'Danag',
	'Trumborr',
	'Zelotah',
	'Altan',
	'Kunoichi',
	'Corvis',
	'Skathix',
	'Nazana',
	'Aothar',
	'Aothar',
	'Cillian',
	'Astralon',
	'Reliquary Tender',
	'Doomscreech',
	'Torturehelm',
	'Vergumkaar',
	'Spider',
	'Coffin Smasher',
	'Boragar',
	'Basilisk',
	'Foli',
	'Daithi',
	'Lodric',
	'Seducer',
	'Gnarlhorn',
	'Goffred',
	'Lord Shazar',
	'Khafru',
	'Pyxniel',
	'Alika',
	'Sepulcher Sentinel',
	'Taurus',
	'Grohak',
	'Versulf',
	'Ultan',
	'Sinesha',
	'Sinesha',
	'Gorgorab',
	'Faceless',
	'Ceez',
	'Big \'Un',
	'Akoth',
	'War Mother',
	'Skimfos',
	'Cardinal',
	'Crimson Helm',
	'Peydma',
	'Broadmaw',
	'Dark Elhain',
	'Fortus',
	'Siegehulk',
	'Islin',
	'Ultimate Galek',
	'Occult Brawler',
	'Luria',
	'Djamarsa',
	'Supreme Athel',
	'Thea',
	'Galkut',
	'Skytouched Shaman',
	'Woad-Painted',
	'Spirithost',
	'Gaius',
	'Bystophus',
	'Mortu-Macaab',
	'Oathbound',
	'Fellhound',
	'Samson',
	'Scabrius',
	'Sachi',
	'Endalia',
	'Hoskarul',
	'Jorrg',
	'Grizzled Jarl',
	'Deliana',
	'Shirimani',
	'Hakkorhn',
	'Fenshi',
	'Ghrukkus',
	'Ankora',
	'Tramaria',
	'Skeuramis',
	'Tallia',
	'Valerie',
	'Taya',
	'Soulbond Bowyer',
	'Skartorsis',
	'Errol',
	'Black Knight',
	'Black Knight',
	'Anax',
	'Lightsworn',
	'Malkith',
	'Bloodgorged',
	'Weregren',
	'Lanakis',
	'Ironclad',
	'Fatalis Blademaster',
	'Brakus',
	'Pestilus',
	'Nari',
	'Helior',
	'Vergis',
	'Gurptuk',
	'Survivor',
	'Battlesage',
	'Yoshi',
	'Warchief',
	'Gurgoh',
	'Tormin',
	'Basher',
	'Fylja',
	'Longbeard',
	'Bellower',
	'Mother Cybele',
	'Alsgor',
	'Vizier Ovelis',
	'Elenaril',
	'Vrask',
	'Oboro',
	'Gwynneth ',
	'King Garog',
	'Lua',
	'Morag',
	'Heiress',
	'Teela',
	'Pann',
	'Shatterbones',
	'Inithwe',
	'Frozen Banshee',
	'Skullcrusher',
	'Criodan',
	'Paragon',
	'Aina',
	'Maranix',
	'Athel',
	'Aleksandr',
	'Ethlen',
	'Kaiden',
	'Robar',
	'Apothecary',
	'Warmaiden',
	'Nobel',
	'Astralith',
	'Isbeil',
	'Wurlim',
	'Gorlos',
	'Timit',
	'Zargala',
	'Hope',
	'Cruetraxa',
	'Marquess',
	'Cleopterix',
	'Visionary',
	'Klodd',
	'Wuzgar',
	'Kellan',
	'Bambus',
	'Steelskull',
	'Angar',
	'Tirlac',
	'Lonatharil',
	'Shieldguard',
	'Fodbor',
	'Sigmund',
	'Graybeard',
	'Lugan',
	'Burangiri',
	'Genzin',
	'Tarshon',
	'Tuhak',
	'Armina',
	'Rhazin',
	'Berserker',
	'Kallia',
	'Shaman',
	'Atur',
	'Bogwalker',
	'Bloodbraid',
	'Missionary',
	'Hellgazer',
	'Jotunn',
	'Margrave',
	'Margrave',
	'Outlaw Monk',
	'Krakarth',
	'Defiled Sinner',
	'Alaric',
	'Chaplain',
	'Confessor',
	'Torrux',
	'Catacomb Councilor',
	'Souldrinker',
	'Vagabond',
	'Fleshmonger',
	'Bone Knight',
	'Crypt Witch',
	'Abyssal',
	'Lady Eresh',
	'Hound Spawn',
	'Towering Titan',
	'Banshee',
	'Veteran',
	'Chonoru',
	'Thenasil',
	'Zephyr Sniper',
	'Elhain',
	'Colwyn',
	'Chancellor Yasmin',
	'Exemplar',
	'Deathless',
	'Arcanist',
	'Sikara',
	'Erinyes',
	'Marquis',
	'Eva',
	'Reinbeast',
	'Temptress',
	'Hordin',
	'Bonekeeper',
	'Tigersoul',
	'Mystic Hand',
	'Baroth',
	'Lordly Legionary',
	'Skullsworn',
	'Yaga',
	'Phranox',
	'Executioner',
	'Karam',
	'Kytis',
	'Chevalier',
	'Jurojin',
	'Elegaius',
	'Rockbeast',
	'Tainix',
	'Fortress Goon',
	'Luthiea',
	'Luthiea',
	'Flesh-Tearer',
	'Hellborn',
	'Crimson Slayer',
	'Nogoryo',
	'Broodlord',
	'Mother Superior',
	'Bushi',
	'Wuji',
	'Loneblade Riab',
	'Jarang',
	'Bloodfeather',
	'Gator',
	'Haarken',
	'Chani',
	'Anointed',
	'Retainer',
	'Corpulent Cadaver',
	'Dirandil',
	'Adriel',
	'Azure',
	'Pitiless One',
	'Purgator',
	'Channeler',
	'Muckstalker',
	'Gladiator',
	'Warden',
	'Captain Temila',
	'Myrmidon',
	'Infernal Baroness',
	'Guardian',
	'Rowan',
	'Mistress',
	'Lady Quilen',
	'Jinglehunter',
	'Canoness',
	'Interceptor',
	'Saurus',
	'Relickeeper',
	'Bloodpainter',
	'Acolyte',
	'Delver',
	'Delver',
	'Diabolist',
	'Grappler',
	'Dark Athel',
	'Maeve',
	'Lich',
	'Metalshaper',
	'Wyrennon',
	'Kinagashi',
	'Little Miss Annie',
	'Flannan',
	'Loriaca',
	'Minaya',
	'Gala',
	'Draconis',
	'Avir',
	'Mezomel - Base',
	'Drokgul',
	'Raf-Matab',
	'Sanguinia',
	'Lady Annabelle',
	'Rugnor',
	'Ursine Ironhide',
	'Gory',
	'Juliana',
	'Lorn',
	'Suiren',
	'Odachi',
	'Harvest Jack',
	'Merouka',
	'Mountain King',
	'Yelagirna',
	'Sir Artimage',
	'Castigator',
	'Balthus',
	'Bovos',
	'Master Butcher',
	'Anchorite',
	'Aeshma',
	'Narma',
	'Roric',
	'Liburga',
	'Fren\'zi',
	'Arndulf',
	'Tagoar',
	'Eolfrig',
	'Painsmith',
	'Duedan',
	'Andryssia',
	'Gerhard',
	'Opardin',
	'Necrohunter',
	'Tatsu',
	'Saito',
	'Kurzad',
	'Jingwon',
	'Karnage - Base',
	'Duhr',
	'Nogdar',
	'Masamoto',
	'Cait',
	'Arix',
	'Gravechill',
	'Var-Gall',
	'Dilgol',
	'Urticata',
	'Ailil',
	'Aeila',
	'Gamuran',
	'Corpse Collector',
	'Suwai',
	'Pharsalas',
	'Bulwark',
	'Jailer',
	'Tomoe',
	'Ilysinya',
	'Hoforees',
	'Shamrock',
	'Siegfrund - Base',
	'Rearguard Sergeant',
	'Ambassador Lethelin',
	'Knott',
	'Geargrinder',
	'Valla',
	'Selinia',
	'Samar',
	'Cromax',
	'Rock Breaker',
	'Giscard',
	'Locwain',
	'Quargan',
	'Guurda',
	'Cormac',
	'Dagger',
	'Carlinia',
	'Suzerain Katonn',
	'Misericord',
	'Adjudicator',
	'Arbalester',
	'Archer',
	'Ashwalker',
	'Assassin',
	'Baerdal',
	'Beast Wrestler',
	'Bergoth',
	'Bloodmask',
	'Bloatwraith',
	'Bombardier',
	'Boltsmith',
	'Branchweaver',
	'Cagebound',
	'Cagebreaker',
	'Candleguard',
	'Cataphract',
	'Centurion',
	'Chopper',
	'Commander',
	'Conquerer',
	'Conscript',
	'Courtier',
	'Crossbowman',
	'Cudgeler',
	'Daywalker',
	'Death Hound',
	'Deathchanter',
	'Deathknight',
	'Dolor',
	'Dunestrider',
	'Elder',
	'Elfguard',
	'Enda',
	'Eviscerator',
	'Excruciator',
	'Fanatic',
	'Fang Cleric',
	'Fencer',
	'Fearmonger',
	'Flesheater',
	'Flailer',
	'Flinger',
	'Frostbringer',
	'Furystoker',
	'Galek',
	'Ginro',
	'Gloril',
	'Goremask',
	'Grandmaster',
	'Grinner',
	'Grimskin',
	'Grumbler',
	'Grunch',
	'Ghoulish Ranger',
	'Halberdier',
	'Haruspex',
	'Harvester',
	'Hatchet Slinger',
	'Headsman',
	'Hellfreak',
	'Hellfang',
	'Hexia',
	'Hexweaver',
	'Hill Nomad',
	'Honor Guard',
	'Huntress',
	'Hurler',
	'Hyria',
	'Ifrit',
	'Infiltrator',
	'Itinerant',
	'Jizoh',
	'Judge',
	'Judicator',
	'Justiciar',
	'Knight-Errant',
	'Lamellar',
	'Lamibur',
	'Lady Etessa',
	'Lifetaker',
	'Line Infantry',
	'Lumberer',
	'Madman',
	'Magister',
	'Magmablood',
	'Magus',
	'Maiden',
	'Marauder',
	'Marksman',
	'Marked',
	'Medicus',
	'Militia',
	'Mycolus',
	'Oldbeard',
	'Ordinator',
	'Outrider',
	'Ox',
	'Panthera',
	'Penitent',
	'Perforator',
	'Petrifya',
	'Pigsticker',
	'Pit Cur',
	'Pitspawn',
	'Pounder',
	'Preserver',
	'Prundar',
	'Prosecutor',
	'Quaestor',
	'Ragemonger',
	'Raider',
	'Ranger',
	'Renouncer',
	'Ripperfist',
	'Ripper',
	'Riscarm',
	'Rocktooth',
	'Romero',
	'Rotting Mage',
	'Ruffstone',
	'Runic Warder',
	'Sanctum Protector',
	'Scion',
	'Scrapper',
	'Seneschal',
	'Sentinel',
	'Siegebreaker',
	'Skink',
	'Skirmisher',
	'Slasher',
	'Slayer',
	'Slitherbrute',
	'Sniper',
	'Snorting Thug',
	'Sorceress',
	'Spymaster',
	'Steadfast Marshal',
	'Steel Bowyer',
	'Stitched Beast',
	'Stout Axeman',
	'Swordsman',
	'Terrorbeast',
	'Teshada',
	'Theurgist',
	'Theresc',
	'Tolf',
	'Tolog',
	'Tormentor',
	'Totem',
	'Tracker',
	'Trugorr',
	'Twinclaw',
	'Umetogi',
	'Ursine Icecrusher',
	'Vanguard',
	'Vildrax',
	'Wagonbane',
	'Wanderer',
	'Warpriest',
	'Witness',
	'Wyvernbane',
	'Yeoman',
	'Zii',
	'Drillmaster',
	'Cultist',
	'Warboy',
	'Magekiller',
	'Frontline Warrior',
	'Crusader',
	'Avenger',
	'Intercessor',
	'Admonitor',
	'Malbranche',
	'Head Taker',
	'Stalwart',
	'Thrasher',
	'Slicer',
	'Vigilante',
	'Aristocrat',
	'Pilgrim',
	'Sergeant',
	'Chemist',
	'Frostskin',
	'Skullsquire',
	'Sister Militant',
	'Skellag',
	'Thrall',
	'Jaeger',
	'Dead Crusader',
	'Bandit',
	'Battle Sister',
	'Incubus',
	'Dervish',
	'Harrier',
	'Lemure',
	'Duelist',
	'Dhampir',
	'Novitiate',
	'Heartpiercer',
	'Warchanter',
	'Solaris',
	'Brute',
	'Lurker',
	'Tunnel Steward',
	'Skinner',
	'Satyr',
	'Sandbow',
	'Icebound',
	'Crusher',
	'Axeman',
	'Ritualist',
	'Suntribe',
	'Windtalker',
	'Pit Fighter',
	'Pikeman',
	'Hungerer',
	'Throatcutter',
	'Redeemer',
	'Stalker',
	'Outlander',
	'Squire',
	'Spiritwalker',
	'Bloodhorn',
	'Vulpine',
	'Spikehead',
	'Word Bearer',
	'Bully',
	'Vilespawn',
	'Preacher',
	'Troglodyte',
	'Knecht',
	'Hardscale',
	'Hellhound',
	'Herald',
];



module.exports = {
	championListAutocomplete,
};